description: "About the trainingThe session is designed to provide an overview of\
  \ what board members need to know about risk and risk management, the key principles\
  \ of risk management and how risk should factor into key decision-making. We will\
  \ also examine other risk concepts including risk culture and appetite at board\
  \ level, as well as exploring the responsibilities of board members in relation\
  \ to risk in their co-ops.FormatThis training course will take place online for\
  \ 2\_hoursA presentation will be delivered alongside practical tasks, opportunities\
  \ for interaction and a Q&A sessionA break will be incorporated within the training\
  \ courseHow much does it cost?\xA365\_+ VAT for members of Co-operatives UK.\xA3\
  90\_+ VAT for non-members. Co-operatives UK members receive 30% off all paid events\
  \ \u2013 plus LOTS more benefits. Learn about\_Co-operatives UK membership.What\
  \ attendees will learnThe responsibilities of board members in terms of risk within\
  \ their co-op (as determined by the Co-operative Corporate Governance Code)An understanding\
  \ of how developing a risk culture in their co-ops can support their co-op\u2019\
  s successKey risk management concepts \u2013 identification and assessment of risksHow\_\
  to determine the strength of the control environment of their co-opsWho should attend?Board\
  \ members who may be new to their role as directorsBoard members of an organisation\
  \ that is relatively new to its risk journeyThose who support the BoardAbout the\
  \ trainerClaire Dalton is a Chartered Governance Professional with 17 years experience\
  \ as a company and society secretary and is a Fellow member of the Governance Institute.\
  \ Claire has spent her career advising on governance matters to many different types\
  \ of organisations including co-ops, companies, charities and regulated businesses.\
  \ As well as corporate governance, Claire has experience in risk management, large\
  \ financial projects, corporate restructuring and compliance.Recording the trainingThis\
  \ training course will be recorded and shared with training participants afterwards.\
  \ The recording will be available for one\_month after the training date. If you\
  \ are unable to attend on the stated date, you can still book on to receive the\
  \ recording link.Cancellations policyAny cancellations made within 28 days are subject\
  \ to full payment with no refund. Name swaps and deferrals can be made free of charge\
  \ until the day of the event. Please contact us via\_[email\_protected] to discuss.\n\
  \      \n    \n  \n\n\n                  Book now"
end: Wednesday 13 November 2024, 12:00pm
event_type: Training
location: Online
price: "\xA365 + VAT for members of Co-operatives UK \xA390 + VAT for non-members"
start: Wednesday 13 November 2024, 10:00am
title: 'Training: Co-ops: An introduction to risks in the boardroom'
url: https://www.uk.coop/events-and-training/events-calendar/training-co-ops-introduction-risks-boardroom
