description: "About the trainingThis 1.5-hour online session will consist of content\
  \ delivered by Co\u2011operative UK\u2019s Governance\_Advisor, Dane Pollard. Dane\
  \ will explain the differences between a standard, non\u2011charitable CBS and a\
  \ CBS with wholly charitable rules.\_There will then be a Q&A session for practitioners\
  \ to explore issues they are facing or further questions they have about the different\
  \ models.Practitioners are encouraged to read the Charities SORP Information Sheet\
  \ in relation to the preparation of accounts for charitable community benefit societies\
  \ \u2013 with specific reference to their use of community shares, i.e. withdrawable,\
  \ non\u2011transferable share capital.\_This information sheet has been developed\
  \ by the Co\u2011operative and Community Capital Committee at Co\u2011operatives\
  \ UK, in partnership with the SORP\u2011making body.We encourage participants to\
  \ send in their questions in advance so that they can be considered for the session.\
  \ An email address to send your questions to will be provided with confirmation\
  \ of your booking.\_We would also like to hear from practitioners to see if they\
  \ would be interested in a follow-up event focusing on accountancy and alignment\
  \ with this SORP.FormatThis training course will take place online for 1.5\_hoursA\
  \ presentation will be delivered, followed by a Q&A sessionHow much does it cost?\xA3\
  50\_+ VAT for members of Co\u2011operatives UK\xA372 + VAT for non\u2011membersWhat\
  \ attendees will learnThe differences between a standard, non-charitable CBS and\
  \ a CBS with wholly charitable rules.Who should attendCommunity shares practitioners\
  \ keen to increase their knowledge and understanding of the charitable CBS model.Existing\
  \ community benefit societies that are considering changing to the charitable model.Groups\
  \ that are considering constituting as a charitable CBS.\_Group bookings: For five\
  \ or more people from one organisationOur standard training courses can take a maximum\
  \ of four people from any one organisation. If you have five or more people interested\
  \ in one course, we:Highly recommend a bespoke in-house training courseCan\_tailor\
  \ the course content to suit the needs of your organisation\u2019s size and modelPlease\
  \ get in touch with our Advice Team at\_[email\_protected]\_to get a quote and date\
  \ availability from our trainers.About the trainerDane Pollard\_works in our Advice\
  \ Team and is the first point of contact for all governance and legal enquiries.\
  \ He specialises in providing advice and guidance to new start co\u2011operatives\
  \ and mutuals looking to incorporate, and he supports all types of co\u2011ops with\
  \ their governance arrangements, processes and policies. Dane also acts as account\
  \ manager to members that have set up in the last two years and provides guidance\
  \ to them on all aspects of their governance calendar. He has many years of experience\
  \ dealing with customers in the retail sector, as well as clients in the corporate\
  \ world.Recording the trainingThis training course will be recorded and shared with\
  \ training participants afterwards. The recording will be available for one\_month\
  \ after the training date. If you are unable to attend on the stated date, you can\
  \ still book on to receive the recording link.Cancellations policyAny cancellations\
  \ made within 28 days are subject to full payment with no refund.\_Name swaps\_\
  and\_deferrals\_can be made free of charge until the day of the event. Please contact\
  \ us via\_[email\_protected]\_to discuss.\n      \n    \n  \n\n\n              \
  \    BOOK HERE"
end: Thursday 13 March 2025, 11:30am
event_type: Training
location: Online via Zoom
price: "\xA350 + VAT for members of Co\u2011operatives UK, \xA372 + VAT for non\u2011\
  members"
start: Thursday 13 March 2025, 10:00am
title: 'Training: All about charitable community benefit societies'
url: https://www.uk.coop/events-and-training/events-calendar/training-all-about-charitable-community-benefit-societies
