description: "Join Dane Pollard from Co\u2011operatives UK for this online training\_\
  on Thursday 10 October from 10am\u201112.30pm.\_About the trainingWho can be on\
  \ a co-operative\u2019s board of directors? What are their legal responsibilities?This\
  \ training covers these issues and all other essentials required to be an effective\
  \ member of the Board of a co-op. Join us for both a theory-led and practical session\
  \ delivered by experienced professional trainers.This training\_provides all the\
  \ essentials a successful co-operative director needs. The session will focus on\
  \ the legal and governance knowledge required, as well as the 'softer' skills needed\
  \ to support and build relationships.FormatThis training course will take place\
  \ online for 2.5\_hoursA presentation will be delivered, followed by a Q&A session.A\
  \ break will be incorporated within the training courseHow much does it cost?\xA3\
  65\_+ VAT for members of Co-operatives UK.\xA395\_+ VAT for non-members. Co-operatives\
  \ UK members receive 30% off all paid events \u2013 plus LOTS more benefits. Learn\
  \ about\_Co-operatives UK membership.What attendees will learnThe legal duties,\
  \ roles and responsibilities of a director and the practical application of these\
  \ duties in relation to your role.How to be an effective director and what attributes\
  \ and skills a \u2018perfect director\u2019 would have in a co-op.What the role\
  \ of the board is and the directors place within it and in relation to the members\
  \ and the employees.What makes an effective board and how you can contribute towards\
  \ a high performing board.Who should attendIf you have recently been appointed to\
  \ the Board of a co-op.You are thinking about becoming a director.You want a refresher\
  \ \u2013 even for more experienced directors.About the trainerDane works in our\
  \ Advice team and is the first point of contact for all governance and legal enquiries.\
  \ Dane specialises in providing advice and guidance to new start co-operatives and\
  \ mutuals looking to incorporate and supports all types of co-ops with their governance\
  \ arrangements, processes and policies.Dane also acts as account manager to members\
  \ that have set up in the last two years and provides guidance to them on all aspects\
  \ of their governance calendar. He has many years of experience dealing with customers\
  \ in the retail sector as well as clients in the corporate world.Recording the trainingThis\
  \ training course will be recorded and shared with training participants afterwards.\
  \ The recording will be available for one\_month after the training date. If you\
  \ are unable to attend on the stated date, you can still book on to receive the\
  \ recording link.Cancellations policyAny cancellations made within 28 days are subject\
  \ to full payment with no refund. Name swaps and deferrals can be made free of charge\
  \ until the day of the event. Please contact us via\_[email\_protected] to discuss.---This\
  \ training course is now full. Please email [email\_protected] to be added to the\
  \ waiting list."
end: Thursday 10 October 2024, 12:30pm
event_type: Training
location: Online via Zoom Meeting
price: "\xA365 + VAT for members of Co-operatives UK \xA395 + VAT for non-members"
start: Thursday 10 October 2024, 10:00am
title: 'Training: Essential co-op director'
url: https://www.uk.coop/events-and-training/events-calendar/training-essential-co-op-director-6
