description: "About the trainingWhat is risk? What is risk management? Why is it important\
  \ to manage risks? The training session covers these elements and other essentials\
  \ to provide attendees with an understanding of risk and how to handle risk in their\
  \ co-ops. Join us for this theory-led session which will also include practical\
  \ and interactive elements.FormatThis training course will take place online for\
  \ 2.5 hoursA presentation will be delivered alongside practical tasks, opportunities\
  \ for interaction and a Q&A sessionA break will be incorporated within the training\
  \ courseHow much does it cost?\xA365\_+ VAT for members of Co-operatives UK.\xA3\
  90\_+ VAT for non-members. Co-operatives UK members receive 30% off all paid events\
  \ \u2013 plus LOTS more benefits. Learn about\_Co-operatives UK membership.What\
  \ attendees will learnThe concept of risk and the different typesThe importance\
  \ of risk managementKey risk management elements and how they workThe importance\
  \ of a strong risk culture in co-opsWho should attend?Anyone new to risk and wants\
  \ to learn moreThose who want to further understand risk and risk management and\
  \ the role it plays in their co-op\_or have a refresherAbout the trainerClaire Dalton\
  \ is a Chartered Governance Professional with 17 years experience as a company and\
  \ society secretary and is a Fellow member of the Governance Institute. Claire has\
  \ spent her career advising on governance matters to many different types of organisations\
  \ including co-ops, companies, charities and regulated businesses. As well as corporate\
  \ governance, Claire has experience in risk management, large financial projects,\
  \ corporate restructuring and compliance.Recording the trainingThis training course\
  \ will be recorded and shared with training participants afterwards. The recording\
  \ will be available for one\_month after the training date. If you are unable to\
  \ attend on the stated date, you can still book on to receive the recording link.Cancellations\
  \ policyAny cancellations made within 28 days are subject to full payment with no\
  \ refund. Name swaps and deferrals can be made free of charge until the day of the\
  \ event. Please contact us via\_[email\_protected] to discuss.\n      \n    \n \
  \ \n\n\n                  Book now"
end: Wednesday 24 April 2024, 12:30pm
event_type: Training
location: Online
price: "\xA365 + VAT for members of Co-operatives UK \xA390 + VAT for non-members"
start: Wednesday 24 April 2024, 10:00am
title: 'Training: Essential co-op risk'
url: https://www.uk.coop/events-and-training/events-calendar/training-essential-co-op-risk
