description: "About the trainingA co-operative's Secretary is central to ensuring\
  \ good governance within a co-op.The most effective secretaries will be trusted\
  \ advisors to the board. They will deliver essential services to ensure the well-being\
  \ of their co-op. This applies to the legal operation, administration as well as\
  \ compliance with corporate governance best practice.In this training, learn the\
  \ essentials a successful co-operative secretary needs. From the legal and governance\
  \ knowledge required, to the 'softer' skills needed to support and build relationships\
  \ with the board of directors.FormatThis training course will take place online\
  \ for 2.5\_hoursA presentation will be delivered, followed by a Q&A session.A break\
  \ will be incorporated within the training courseHow much does it cost?\xA365\_\
  + VAT for members of Co-operatives UK.\xA395\_+ VAT for non-members. Co-operatives\
  \ UK members receive 30% off all paid events \u2013 plus LOTS more benefits. Learn\
  \ about\_Co-operatives UK membership.What attendees will learnLearn the skills and\
  \ qualities required for a co-op secretary \u2013 and how a secretary can carry\
  \ out their role effectively. This includes:The legal duties and responsibilities\
  \ of a secretary.The practical application of these duties.Statutory reporting and\
  \ paperwork requirements.Understanding best practice for co-op secretaries.Who should\
  \ attendThose new to the co-op secretary role as it deals with the main legal and\
  \ best practice responsibilities associated with the role.Existing secretaries wanting\
  \ a refresher and an update on any key changes.Interested in attending Secretary\
  \ I and Secretary IIGet a discount when booking onto both training courses at the\
  \ same timeEmail\_[email\_protected]\_to make your bookings and gain the discount\xA3\
  180 + VAT (discounted from \xA3210) for members of Co-operatives UK\xA3262 + VAT\
  \ (discounted from \xA3305) for non-members. Co-operatives UK members receive 30%\
  \ off all paid events \u2013 plus LOTS more benefits. Learn about Co-operatives\
  \ UK membership.Find out more about Secretary II: Putting learning into practiceAbout\
  \ the trainerDane works in our Advice team and is the first point of contact for\
  \ all governance and legal enquiries. Dane specialises in providing advice and guidance\
  \ to new start co-operatives and mutuals looking to incorporate and supports all\
  \ types of co-ops with their governance arrangements, processes and policies.Dane\
  \ also acts as account manager to members that have set up in the last two years\
  \ and provides guidance to them on all aspects of their governance calendar. He\
  \ has many years of experience dealing with customers in the retail sector as well\
  \ as clients in the corporate world.Recording the trainingThis training course will\
  \ be recorded and shared with training participants afterwards. The recording will\
  \ be available for one\_month after the training date. If you are unable to attend\
  \ on the stated date, you can still book on to receive the recording link.Cancellations\
  \ policyAny cancellations made within 28 days are subject to full payment with no\
  \ refund. Name swaps and deferrals can be made free of charge until the day of the\
  \ event. Please contact us via\_[email\_protected] to discuss.\n      \n    \n \
  \ \n\n\n                  Book now"
end: Thursday 05 September 2024, 12:30pm
event_type: Training
price: "\xA365 + VAT for members of Co-operatives UK \xA395 + VAT for non-members"
start: Thursday 05 September 2024, 10:00am
title: 'Training: Co-op secretary I: The Essentials'
url: https://www.uk.coop/events-and-training/events-calendar/training-co-op-secretary-i-essentials-0
