description: "About the trainingA co\u2011operative\u2019s Secretary is central to\
  \ ensuring good governance within a co\u2011op.The most effective secretaries are\
  \ trusted advisors to the board \u2013 and they deliver essential services to ensure\
  \ the well-being of their co\u2011op. This applies to its legal operation and administration,\
  \ as well as compliance with corporate governance best practice.In this training,\
  \ you\u2019ll learn the essentials a successful co\u2011operative secretary needs\
  \ \u2013 from the required legal and governance knowledge to the \u2018softer\u2019\
  \ skills needed to support and build relationships with the board of directors.FormatThis\
  \ training course will take place online for 2.5\_hoursA presentation will be delivered,\
  \ followed by a Q&A sessionA break will be incorporated within the training courseHow\
  \ much does it cost?\xA370\_+ VAT for members of Co\u2011operatives UK\xA3100\_\
  + VAT for non\u2011members. Co\u2011operatives UK members receive 30% off all paid\
  \ events \u2013 plus LOTS more benefits. Learn about\_Co-operatives UK membershipWhat\
  \ attendees will learnLearn the skills and qualities required for a co\u2011op secretary\
  \ \u2013 and how a secretary can carry out their role effectively. This includes:The\
  \ legal duties and responsibilities of a secretaryThe practical application of these\
  \ dutiesStatutory reporting and paperwork requirementsUnderstanding best practice\
  \ for co\u2011op secretariesWho should attendThose new to the co\u2011op secretary\
  \ role as it deals with the main legal and best practice responsibilities associated\
  \ with the roleExisting secretaries wanting a refresher and an update on any key\
  \ changesInterested in attending Secretary I and Secretary IIGet a discount when\
  \ booking onto both training courses at the same timeEmail\_[email\_protected]\_\
  to make your bookings and gain the discount\xA3220 + VAT (discounted from \xA3250)\
  \ for members of Co\u2011operatives UK\xA3330 + VAT (discounted from \xA3360) for\
  \ non-members. Co\u2011operatives UK members receive 30% off all paid events \u2013\
  \ plus LOTS more benefits. Learn about Co\u2011operatives UK membershipFind out\
  \ more about Co\u2011op secretary II: Putting your learning into practiceAbout the\
  \ trainerDane Pollard works in our Advice Team and is the first point of contact\
  \ for all governance and legal enquiries. He specialises in providing advice and\
  \ guidance to new start co\u2011operatives and mutuals looking to incorporate, and\
  \ he supports all types of co\u2011ops with their governance arrangements, processes\
  \ and policies.Dane also acts as account manager to members that have set up in\
  \ the last two years and provides guidance to them on all aspects of their governance\
  \ calendar. He has many years of experience dealing with customers in the retail\
  \ sector, as well as clients in the corporate world.Recording the trainingThis training\
  \ course will be recorded and shared with training participants afterwards. The\
  \ recording will be available for one\_month after the training date. If you are\
  \ unable to attend on the stated date, you can still book on to receive the recording\
  \ link.Alternative date availableCan\u2019t make this date? No problem! We\u2019\
  re also running the training on Wednesday 16 July, so follow the link to book.\_\
  Cancellations policyAny cancellations made within 28 days are subject to full payment\
  \ with no refund. Name swaps and deferrals can be made free of charge until the\
  \ day of the event. Please contact us via\_[email\_protected] to discuss.\n    \
  \  \n    \n  \n\n\n                  BOOK HERE"
end: Wednesday 05 March 2025, 12:30pm
event_type: Training
location: Online via Zoom
price: "\xA370 + VAT for Co\u2011operatives UK members, \xA3100 + VAT for non\u2011\
  members"
start: Wednesday 05 March 2025, 10:00am
title: "Training: Co\u2011op secretary I: The Essentials \u2013 March 2025"
url: https://www.uk.coop/events-and-training/events-calendar/training-co-op-secretary-i-essentials-march-2025
