description: "About the trainingWe understand that the role of a co\u2011op secretary\
  \ is complex, so we\u2019re running practical in\u2011person follow\u2011up training\
  \ to anyone who has previously attended a co\u2011op secretary session.This further\
  \ training will equip you with a suite of practical plans covering every event in\
  \ an annual governance cycle. It will also ensure you have the knowledge to deliver\
  \ on all your responsibilities as the secretary of your organisation.IMPORTANT:\
  \ This training course does not cover the essential skills required to be a co\u2011\
  op secretary. It is designed for those who have previously attended our\_training:\
  \ Co\u2011op secretary I: The essentials and are looking to put their learning into\
  \ practice.\_FormatThis training course will take place in\u2011person\_for six\_\
  hoursThere will be a number of practical exercises where we\u2019ll support attendees\
  \ to create their governance yearly planThere will be an expectation to engage in\
  \ discussion on governance themes, solve hypothetical (and real) governance problems\
  \ and consult\_constitutional documents to evidence planning decision\u2011makingRefreshments\
  \ and lunch will be providedHow much does it cost?\xA3180\_+ VAT for members of\
  \ Co\u2011operatives UK\xA3260\_+ VAT for non-members. Co\u2011operatives UK members\
  \ receive 30% off all paid events \u2013 plus LOTS more benefits. Learn about\_\
  Co\u2011operatives UK membershipInterested in attending Secretary I and Secretary\
  \ II?Get a discount when booking onto both training courses at the same timeEmail\
  \ [email\_protected] to make your bookings and gain the discount\xA3180 + VAT (discounted\
  \ from \xA3225) for members of Co\u2011operatives UK\xA3262 + VAT (discounted from\
  \ \xA3315) for non-membersWhat attendees will learnHow to actually do the job of\
  \ being a secretaryThe things to think about and when to think about themWhat falls\
  \ within a secretary\u2019s\_remit and how to ensure nothing falls through the cracks\
  \ \u2013 by planning everything in advanceWho should attendThose who have completed\
  \ the Co\u2011operatives UK training: Co-op secretary I: The essentials\_course\
  \ at least three\_months previouslyExperienced secretaries that have not attended\
  \ the above training can contact [email\_protected] to check if the course is suitable\
  \ as a stand-aloneAbout the trainersZena King\_is a Senior Governance Advisor at\
  \ Co\u2011operatives UK. She is a Chartered Company Secretary with more than 10\
  \ years\u2019 experience of co\u2011operative society governance and an academic\
  \ background in Law. Zena was Co\u2011operatives UK\u2019s Society Secretary for\
  \ five years.Zena is accustomed to guiding a non\u2011executive board through discharging\
  \ its responsibilities and effective decision making; being accountable for regulatory\
  \ compliance and implementing corporate governance best practice. She has supported\
  \ boards in developing strategic plans, policies and processes and has direct experience\
  \ of leading internal audits and gap analysis exercises.With experience of effective\
  \ governance systems that facilitate member ownership and control, Zena can offer\
  \ practical solutions for co\u2011operatives to bring together corporate governance\
  \ best practice and the co\u2011operative values and principles. She is also an\
  \ accredited data protection practitioner and, alongside supporting our members,\
  \ leads our own work to ensure compliance with data protection legislation.Zena\
  \ has practical experience in the boardroom too \u2013 she sits on the board of\
  \ Projekts MCR and is a former director of Co\u2011operative and Community Finance.Dane\
  \ Pollard\_works in our Advice Team and is the first point of contact for all governance\
  \ and legal enquiries. Dane specialises in providing advice and guidance to new\
  \ start co\u2011operatives and mutuals looking to incorporate and supports all types\
  \ of co\u2011ops with their governance arrangements, processes and policies.Dane\
  \ also acts as account manager to members that have set up in the last two years\
  \ and provides guidance to them on all aspects of their governance calendar. He\
  \ has many years of experience dealing with customers in the retail sector as well\
  \ as clients in the corporate world.Cancellations policyAny cancellations made within\
  \ 28 days are subject to full payment with no refund. Name swaps and deferrals can\
  \ be made free of charge until the day of the event. Please contact us via\_[email\_\
  protected] to discuss.\n      \n    \n  \n\n\n                  BOOK HERE"
end: Thursday 20 November 2025, 4:00pm
event_type: Training
location: "Co\u2011operatives UK, Holyoake House, Hanover Street, Manchester, M60\
  \ 0AS"
price: "\xA3180 + VAT for Co\u2011operatives UK members, \xA3260 + VAT for non\u2011\
  members"
start: Thursday 20 November 2025, 10:00am
title: "Training: Co-op secretary II: Putting your learning into practice \u2013 November\
  \ 2025"
url: https://www.uk.coop/events-and-training/events-calendar/training-co-op-secretary-ii-putting-your-learning-practice-2
