description: "About the trainingThis practical session will give you a general understanding\
  \ of HR and employment law.By the end of the session you will understand the key\
  \ rights and responsibilities associated with employing people and what you need\
  \ to do to ensure that your co-op is compliant with these, from recruitment all\
  \ the way through to the end of the employment relationship.Important for consumer\
  \ and worker co-ops alike, this session is ideal for those just starting out on\
  \ their HR careers or those with little or no experience of HR who may find themselves\
  \ responsible for managing HR within their organisation.FormatThis training\_will\
  \ be hosted online for 3.5\_hours on both 2\_and 3\_October.\_Attendees will need\
  \ to attend both days.A mix of presentation, Q&A and breakout sessions.\_Refreshment\
  \ breaks will be incorporated.\_How much does it cost?\xA3125\_+ VAT for members\
  \ of Co-operatives UK\xA3180\_+ VAT for non-members. Co-operatives UK members receive\
  \ 30% off all paid events \u2013 plus LOTS more benefits. Learn about\_Co-operatives\
  \ UK membership.What attendees will learnBy the end of this session you will know:How\
  \ to ensure a fair recruitment process.The minimum requirements for contracts of\
  \ employment and essential policies and procedures.What you need to consider when\
  \ managing employees with regard to their pay, when they take time off and when\
  \ disciplinary or grievance matters arise.What the employer\u2019s obligations are\
  \ when the employment relationship ends.Who should attendPeople just starting an\
  \ HR career.Co-ops that are just starting to employ people.individuals with little\
  \ or no HR experience who may be expected to manage HR as part of their role.About\
  \ the trainersGary has a wealth of experience in the field of employment law, having\
  \ previously worked as an ACAS officer and for the Employment Tribunals before qualifying\
  \ as a solicitor at DWF solicitors. Gary has worked as a solicitor with the Co-operative\
  \ Group and many independent co-operatives as part of the Co-operative Employers\
  \ Association and is a very experienced Employment Tribunal advocate and his knowledge\
  \ and experience extend to all aspects of employment law including complex areas\
  \ such as TUPE and discrimination.Kate is an experienced HR professional with almost\
  \ 15 years' experience in HR policy, reward and employee relations in co-operatives.\
  \ A chartered member of the CIPD specialising in all things policy, Kate is well\
  \ placed to provide expert advice, guidance and support on all aspects of the employment\
  \ journey.Recording the trainingThis training course will be recorded and shared\
  \ with training participants afterwards. The recording will be available for one\_\
  month after the training date. If you are unable to attend on the stated date, you\
  \ can still book on to receive the recording link.Cancellations policyAny cancellations\
  \ made within 28 days are subject to full payment with no refund. Name swaps and\
  \ deferrals can be made free of charge until the day of the event. Please contact\
  \ us via\_[email\_protected] to discuss.\n      \n    \n  \n\n\n               \
  \   Book now"
end: Thursday 03 October 2024, 1:00pm
event_type: Training
location: Online via Zoom Meeting
price: "\xA3125 + VAT for members of Co-operatives UK \xA3180 + VAT for non-members"
start: Wednesday 02 October 2024, 9:30am
title: 'Training: HR Overview for co-ops'
url: https://www.uk.coop/events-and-training/events-calendar/training-hr-overview-co-ops-0
