description: "About the trainingWe understand that the role of a co-op secretary is\
  \ complex. After the success of last year's training course, we are continuing to\
  \ run an in-person session to provide further support and practical training to\
  \ anyone who has previously attended our Essential Co-op Secretary training.\_\_\
  This further training will equip you with a suite of practical plans covering every\
  \ event in an annual governance cycle. We will also ensure you have the knowledge\
  \ to deliver on all your responsibilities as secretary of your organisation.IMPORTANT:\
  \ This training course does not cover the essential skills required to be a co-op\
  \ secretary. It is designed for those that have previously attended our\_Training:\
  \ Co-op secretary I: The essentials and looking to put their learnings into practice.\_\
  FormatThis training course will take place in-person\_for 6\_hoursThere will be\
  \ a number of practical exercises where we\u2019ll support attendees to create their\
  \ governance yearly planThere will be an expectation to engage in discussion on\
  \ governance themes, solve hypothetical (and real) governance problems and consult\_\
  constitutional documents to evidence the planning decision-makingRefreshments and\
  \ lunch will be providedHow much does it cost?\xA3160\_+ VAT for members of Co-operatives\
  \ UK.\xA3220\_+ VAT for non-members. Co-operatives UK members receive 30% off all\
  \ paid events \u2013 plus LOTS more benefits. Learn about\_Co-operatives UK membership.Interested\
  \ in attending Secretary I and Secretary IIGet a discount when booking onto both\
  \ training courses at the same timeEmail [email\_protected] to make your bookings\
  \ and gain the discount\xA3180 + VAT (discounted from \xA3225) for members of Co-operatives\
  \ UK\xA3262 + VAT (discounted from \xA3305) for non-members. Co-operatives UK members\
  \ receive 30% off all paid events \u2013 plus LOTS more benefits. Learn about Co-operatives\
  \ UK membership.What attendees will learnHow to actually do the job of being a secretaryThe\
  \ things to think about and when to think about themWhat falls within a secretaries\_\
  remit and how to ensure nothing falls through the cracks (\u2026by planning everything\
  \ in advance)Who should attendThose who have completed the Co-operatives UK training:\
  \ Co-op secretary I: The essentials\_course at least 3\_months ago.Experienced secretaries\
  \ that have not attended the training: Co-op secretary I: The essentials course\
  \ can contact [email\_protected] to check if the course is suitable as a stand-alone.About\
  \ the trainersZena King\_is a Senior Governance Advisor at Co-operatives UK - a\
  \ Chartered Company Secretary with more than ten years\u2019 experience of co-operative\
  \ society governance and an academic background in Law; she was Co-operatives UK\u2019\
  s Society Secretary for five years.Zena is accustomed to guiding a non-executive\
  \ board through discharging its responsibilities and effective decision making;\
  \ being accountable for regulatory compliance and implementing corporate governance\
  \ best practice. Zena has supported boards in developing strategic plans, policies\
  \ and processes and has direct experience of leading internal audits and gap analysis\
  \ exercises.With experience of effective governance systems that facilitate member\
  \ ownership & control, Zena can offer practical solutions for co-operatives to bring\
  \ together corporate governance best practice and the co-operative values & principles.\
  \ Zena is also an accredited data protection practitioner and, alongside supporting\
  \ our members, leads our own work to ensure compliance with data protection legislation.Zena\
  \ has practical experience in the boardroom too \u2013 she sits on the board of\
  \ Projekts MCR and is a former director of Co-operative and Community Finance.Dane\
  \ Pollard\_works in our Advice team and is the first point of contact for all governance\
  \ and legal enquiries. Dane specialises in providing advice and guidance to new\
  \ start co-operatives and mutuals looking to incorporate and supports all types\
  \ of co-ops with their governance arrangements, processes and policies.Dane also\
  \ acts as account manager to members that have set up in the last two years and\
  \ provides guidance to them on all aspects of their governance calendar. He has\
  \ many years of experience dealing with customers in the retail sector as well as\
  \ clients in the corporate world.Cancellations policyAny cancellations made within\
  \ 28 days are subject to full payment with no refund. Name swaps and deferrals can\
  \ be made free of charge until the day of the event. Please contact us via\_[email\_\
  protected] to discuss."
end: Thursday 09 May 2024, 4:00pm
event_type: Training
location: Co-operatives UK, Holyoake House, Hanover Street, Manchester, M60 0AS
price: "\xA3160 + VAT for members of Co-operatives UK \xA3220 + VAT for non-members"
start: Thursday 09 May 2024, 10:00am
title: 'Training: Co-op secretary II: Putting your learning into practice'
url: https://www.uk.coop/events-and-training/events-calendar/training-co-op-secretary-ii-putting-your-learning-practice-0
