description: "About the trainingThis session will explore how to write a business\
  \ plan.It will break down and walk participants through a step by step process between\
  \ having a business idea and a completed business plan. This will include, checking\
  \ your business idea and creating a marketing plan, working out how much it will\
  \ cost to enact your idea, financing that cost, deciding on the best legal structure\
  \ and governance model for your business and creating detailed financial projections.As\
  \ well as the detailed specifics for each step the workshop will also provide general\
  \ guidance on how best to pitch your business plan.FormatThis training\_will be\
  \ hosted online for 4 hours on both 11\_and 12\_September.\_Attendees will need\
  \ to attend both days.A mix of presentation, Q&A and breakout sessions.\_Refreshment\
  \ breaks will be incorporated.\_How much does it cost?\xA3130 + VAT for members\
  \ of Co-operatives UK\xA3180\_+ VAT for non-members. Co-operatives UK members receive\
  \ 30% off all paid events \u2013 plus LOTS more benefits. Learn about\_Co-operatives\
  \ UK membership.What you will learnHow to write a business planWhat should go in\
  \ a business planHow is a business plan best structured to tell a coherent storyWho\
  \ should attendAnyone who is either trying to start a new co-op, grow their existing\
  \ co-op, needs to raise finance or is looking for a new strategic direction for\
  \ their co-opAny co-op development worker or member of infrastructure bodies that\
  \ support people writing business plans.About the trainerAndrew\_Woodcock is from\
  \ Co-op Culture and Acorn Co-op Support. Andy\_is an experienced trainer with excellent\
  \ communication skills. They have\_great knowledge of participatory techniques and\
  \ has lived and worked in co-ops for the last 20 years.Andy co-manages a \xA3750,000\
  \ co-op loan fund, as well as a co-operative investment fund of almost \xA31million.\
  \ They have helped various co-ops raise over \xA35m of capital as well as being\
  \ treasurer to many co-ops. Andy\_also prepares co-ops accounts.\_Andy co-produced\
  \ the Introduction to Financial Literacy workshop which has now trained over 500\
  \ people in better understanding their co-op's accounts.Recording the trainingThis\
  \ training course will be recorded and shared with training participants afterwards.\
  \ The recording will be available for one\_month after the training date. If you\
  \ are unable to attend on the stated date, you can still book on to receive the\
  \ recording link.Cancellations policyAny cancellations made within 28 days are subject\
  \ to full payment with no refund. Name swaps and deferrals can be made free of charge\
  \ until the day of the event. Please contact us via\_[email\_protected] to discuss.\n\
  \      \n    \n  \n\n\n                  Book now"
end: Thursday 12 September 2024, 1:30pm
event_type: Training
location: Online via Zoom
price: "\xA3125 + VAT for members of Co-operatives UK \xA3180 + VAT for non-members"
start: Wednesday 11 September 2024, 9:30am
title: 'Training: How to write a good business plan'
url: https://www.uk.coop/events-and-training/events-calendar/training-how-write-good-business-plan
