description: "About the trainingThe session is designed to provide an overview of\
  \ what board members need to know about the key principles of risk and risk management\
  \ \u2013 and how risk should factor into key decision\u2011making. We will also\
  \ examine other risk concepts including risk culture and appetite at board level,\
  \ as well as exploring the responsibilities of board members in relation to risk\
  \ in their co\u2011ops.FormatThis training course will take place online for two\
  \ and a half\_hoursA presentation will be delivered alongside practical tasks, opportunities\
  \ for interaction and a Q&A sessionA break will be incorporated within the training\
  \ courseHow much does it cost?\xA370\_+ VAT for members of Co-operatives UK\xA3\
  100\_+ VAT for non-members. Co-operatives UK members receive 30% off all paid events\
  \ \u2013 plus LOTS more benefits. Learn about\_Co-operatives UK membershipWhat attendees\
  \ will learnThe responsibilities of board members in terms of risk within their\
  \ co\u2011op (as determined by the Co\u2011operative Corporate Governance Code)An\
  \ understanding of how developing a risk culture in their co\u2011ops can support\
  \ their co\u2011op\u2019s successKey risk management concepts \u2013 identification\
  \ and assessment of risksHow\_to determine the strength of the control environment\
  \ of their co\u2011opsWho should attend?Board members who may be new to their role\
  \ as directorsBoard members of an organisation that is relatively new to its risk\
  \ journeyThose who support the BoardGroup bookings: For five or more people from\
  \ one organisationOur standard training courses can take a maximum of four people\
  \ from any one organisation. If you have five or more people interested in one course,\
  \ we:Highly recommend a bespoke in-house training courseCan\_tailor the course content\
  \ to suit the needs of your organisation\u2019s size and modelPlease get in touch\
  \ with our Advice Team at [email\_protected] to get a quote and date availability\
  \ from our trainers.About the trainerClaire Dalton is a Chartered Governance Professional\
  \ with 17 years experience as a company and society secretary and is a Fellow member\
  \ of the Governance Institute. Claire has spent her career advising on governance\
  \ matters to many different types of organisations including co\u2011ops, companies,\
  \ charities and regulated businesses. As well as corporate governance, Claire has\
  \ experience in risk management, large financial projects, corporate restructuring\
  \ and compliance.Recording the trainingThis training course will be recorded and\
  \ shared with training participants afterwards. The recording will be available\
  \ for one\_month after the training date. If you are unable to attend on the stated\
  \ date, you can still book on to receive the recording link.Cancellations policyAny\
  \ cancellations made within 28 days are subject to full payment with no refund.\
  \ Name swaps and deferrals can be made free of charge until the day of the event.\
  \ Please contact us via\_[email\_protected] to discuss.\n      \n    \n  \n\n\n\
  \                  BOOK HERE"
end: Wednesday 12 November 2025, 12:30pm
event_type: Training
location: Online via Zoom
price: "\xA370 + VAT for Co\u2011operatives UK members, \xA3100 + VAT for non\u2011\
  members"
start: Wednesday 12 November 2025, 10:00am
title: 'Training: An introduction to risk in the boardroom'
url: https://www.uk.coop/events-and-training/events-calendar/training-introduction-risk-boardroom
