description: "About the trainingThis advanced-level workshop is a must\u2011attend\
  \ for board directors, management committee members and members involved in overseeing\
  \ their co\u2011op.It aims to demystify accountancy and help delegates interpret\
  \ their co\u2011op\u2019s management accounts and use that financial information\
  \ to make informed business decisions.Please note:\_This course is suitable for\
  \ all legal forms. It is not an accountancy course based on what the law says \u2013\
  \ it\u2019s about how to understand accounts and what they mean.\_FormatThis training\_\
  will be hosted online for four hours on both 14 and 15 October\_Attendees will need\
  \ to attend both daysA mix of presentation, Q&A and breakout sessions\_Refreshment\
  \ breaks will be incorporated\_How much does it cost?\xA3150\_+ VAT for members\
  \ of Co\u2011operatives UK\xA3215\_+ VAT for non\u2011members. Co\u2011operatives\
  \ UK members receive 30% off all paid events \u2013 plus LOTS more benefits. Learn\
  \ about\_Co-operatives UK membershipWhat you will learnConcepts of accountingImportance\
  \ of management accounts for making financial decisionsHow to interpret management\
  \ accountsHow to forecast cashflow and interpret cashflow statementsHow to create\
  \ an income statement, profit and loss sheet, and balance sheetFinancial performance\
  \ indicators and what can we learn from themGearing ratios and what we can learn\
  \ from themHow share capital relates to this accounting frameworkWho should attendThe\
  \ course for anyone running co-operative organisations who need to understand and\
  \ make decisions based on financial accounts. For example:Members of a board of\
  \ directorsMembers of a management committeeMembers involved in overseeing the businessGroup\
  \ bookings: For five or more people from one organisationOur standard training courses\
  \ can take a maximum of four people from any one organisation. If you have five\
  \ or more people interested in one course, we:Highly recommend a bespoke in-house\
  \ training courseCan\_tailor the course content to suit the needs of your organisation\u2019\
  s size and modelPlease get in touch with our Advice Team at [email\_protected] to\
  \ get a quote and date availability from our trainers.About the trainerAndrew\_\
  Woodcock is from Co\u2011op Culture and Acorn Co\u2011op Support. An experienced\
  \ trainer with excellent communication skills, they have\_great knowledge of participatory\
  \ techniques and have lived and worked in co\u2011ops for the last 20 years.Andy\
  \ co-manages a \xA3750,000 co\u2011op loan fund, as well as a co\u2011operative\
  \ investment fund of almost \xA31million. They have helped various co-ops raise\
  \ over \xA35m of capital, as well as being treasurer to many co-ops. Andy\_also\
  \ prepares co\u2011ops\u2019 accounts.\_Andy co\u2011produced the Introduction to\
  \ Financial Literacy workshop which has now trained over 500 people in better understanding\
  \ their co\u2011op\u2019s accounts.Recording the trainingThis training course will\
  \ be recorded and shared with training participants afterwards. The recording will\
  \ be available for one\_month after the training date. If you are unable to attend\
  \ on the stated date, you can still book on to receive the recording link.Cancellations\
  \ policyAny cancellations made within 28 days are subject to full payment with no\
  \ refund. Name swaps and deferrals can be made free of charge until the day of the\
  \ event. Please contact us via\_[email\_protected] to discuss.\n      \n    \n \
  \ \n\n\n                  BOOK HERE"
end: Wednesday 15 October 2025, 1:30pm
event_type: Training
location: Online via Zoom
price: "\xA3150 + VAT for Co\u2011operatives UK members, \xA3215 + VAT for non\u2011\
  members"
start: Tuesday 14 October 2025, 9:30am
title: "Training: Understanding your co\u2011op\u2019s finances \u2013 October 2025"
url: https://www.uk.coop/events-and-training/events-calendar/training-understanding-your-co-ops-finances-october-2025
