description: "About the trainingThis practical session will give you a general understanding\
  \ of HR and employment law.By the end of the session you will understand the key\
  \ rights and responsibilities associated with employing people and what you need\
  \ to do to ensure that your co\u2011op is compliant with these, from recruitment\
  \ all the way through to the end of the employment relationship.Important for consumer\
  \ and worker co\u2011ops alike, this session is ideal for those just starting out\
  \ on their HR careers or those with little or no experience of HR who may find themselves\
  \ responsible for managing HR within their organisation.FormatThis training\_will\
  \ be hosted online for 3.5\_hours on both 30 September and 1 OctoberAttendees will\
  \ need to attend both daysA mix of presentation, Q&A and breakout sessionsRefreshment\
  \ breaks will be incorporatedHow much does it cost?\xA3150\_+ VAT for members of\
  \ Co-operatives UK\xA3215\_+ VAT for non-members. Co-operatives UK members receive\
  \ 30% off all paid events \u2013 plus LOTS more benefits. Learn about\_Co-operatives\
  \ UK membership.What attendees will learnBy the end of this session you will know:How\
  \ to ensure a fair recruitment processThe minimum requirements for contracts of\
  \ employment and essential policies and proceduresWhat you need to consider when\
  \ managing employees with regard to their pay, when they take time off and when\
  \ disciplinary or grievance matters ariseWhat the employer\u2019s obligations are\
  \ when the employment relationship endsWho should attendPeople just starting an\
  \ HR careerCo\u2011ops that are just starting to employ peopleIndividuals with little\
  \ or no HR experience who may be expected to manage HR as part of their roleGroup\
  \ bookings: For five or more people from one organisationOur standard training courses\
  \ can take a maximum of four people from any one organisation. If you have five\
  \ or more people interested in one course, we:Highly recommend a bespoke in-house\
  \ training courseCan\_tailor the course content to suit the needs of your organisation\u2019\
  s size and modelPlease get in touch with our Advice Team at [email\_protected] to\
  \ get a quote and date availability from our trainers.About the trainersGary Morrison\
  \ has a wealth of experience in the field of employment law, having previously worked\
  \ as an ACAS officer and for the Employment Tribunals, before qualifying as a solicitor\
  \ at DWF solicitors. A very experienced employment tribunal advocate, he has worked\
  \ as a solicitor with the Co\u2011operative Group and many independent co\u2011\
  operatives as part of the Co\u2011operative Employers Association. His knowledge\
  \ and experience extend to all aspects of employment law, including complex areas\
  \ such as TUPE and discrimination.Kate Fielding is an experienced HR professional\
  \ with almost 15 years\u2019 experience in HR policy, reward and employee relations\
  \ in co\u2011operatives. A chartered member of the CIPD specialising in all things\
  \ policy, Kate is well placed to provide expert advice, guidance and support on\
  \ all aspects of the employment journey.Recording the trainingThis training course\
  \ will be recorded and shared with training participants afterwards. The recording\
  \ will be available for one\_month after the training date. If you are unable to\
  \ attend on the stated date, you can still book on to receive the recording link.Cancellations\
  \ policyAny cancellations made within 28 days are subject to full payment with no\
  \ refund. Name swaps and deferrals can be made free of charge until the day of the\
  \ event. Please contact us via\_[email\_protected] to discuss.\n      \n    \n \
  \ \n\n\n                  BOOK HERE"
end: Wednesday 01 October 2025, 1:00pm
event_type: Training
location: Online via Zoom
price: "\xA3150 + VAT for Co\u2011operatives UK members, \xA3215 + VAT for non\u2011\
  members"
start: Tuesday 30 September 2025, 9:30am
title: "Training: HR overview for co\u2011operatives"
url: https://www.uk.coop/events-and-training/events-calendar/training-hr-overview-co-operatives
